# -------------------------------------------------#
# ğ’ğ“ğ€ğ…ğ… ğŒğ€ğğ€ğ†ğ„ğ‘ - ğ‘«ğ’†ğ’”ğ’‚ğ’“ğ’“ğ’ğ’ğ’ğ’‚ğ’…ğ’ ğ’‘ğ’ğ’“ ğ‘¹ğ’ğ’ğ’‚ğ’ğ’…ğ’ğ’‚ğ’—
# ğ‘«ğ’†ğ’”ğ’‚ğ’“ğ’“ğ’ğ’ğ’ğ’‚ğ’…ğ’ ğ’‘ğ’ğ’“ ğ‘¹ğ’ğ’ğ’‚ğ’ğ’…ğ’ğ’‚ğ’— - RONALDZAV.COM
# -------------------------------------------------#

# ğ‚ğğğ…ğˆğ†ğ”ğ‘ğ€ğ‚ğˆğğ ğ†ğ„ğğ„ğ‘ğ€ğ‹ ----------------- #
bot:
  activity: "ronaldzav.com" # Actividad del bot.
  embedColor: "#ffffff" # Color normal.
  embedErrorColor: "#fc0f03" # Color de error.
  guild: "1144762157041459321" # Id del servidor donde operara.

channels:
  evidences: "1144763005540761631" # Canal donde se enviaran las evidencias.
  waiting: "1144763219915853877" # Id del canal donde las evidencias esperan ser aprobadas.
  alerts: "1144763123501375498" # Id del canal donde llegaran las alertas.

score:
  evidenceAccept: "5" # Cantidad de puntos a sumar por evidencia aceptada
  evidenceDeny: "0" # Cantidad de puntos a restart por evidencia rechazada

strikes:
  limit: "3" # Cantidad de strikes para sancionar al staff.
  sanction: "true" # Remueve el rol de staff al miembro.

roles:
  staff: "1145464512259051680" # Rol de staff.


# ğŒğ„ğğ’ğ€ğ‰ğ„ğ’ ----------------------------------- #
messages:
  embed:
    title: "Staff Manager"
    footer: "Desarrollado por ronaldzav.com"
  
  evidenceChannel:
    content: "EnvÃ­a tus evidencias a este canal, tu mensaje debe contener una imagen y texto. Despues de editar el archivo de configuracion de este mensaje, borre este mensaje del canal de discord para que se vuelva a enviar."
      
  maxStrikes:
    public: "El staff <member> alcanzo el maximo de strikes."
    reply: "El staff <member> alcanzo el maximo de strikes, se envio un aviso a <alertsChannel>"
    